-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 18d7035de5388cc7775be57f529c154bf541aab9
    exclude: 'dotfiles/.less'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-merge-conflict
-   repo: git://github.com/detailyang/pre-commit-shell
    sha: 1fdffa0434cde2b87f19ad258201d3e81481af5f
    hooks:
    -   id: shell-lint
