-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 4ef03c4223ad322c7adaa6c6c0efb26b57df3b71
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: end-of-file-fixer
        exclude: \.less$
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/detailyang/pre-commit-shell
    sha: 1fdffa0434cde2b87f19ad258201d3e81481af5f
    hooks:
    -   id: shell-lint
        exclude: \.zsh$
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
